// Generates VAPID keys for web push (streak reminders) and appends them to the root .env if missing.
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import webpush from "web-push";

const envPath = resolve(dirname(fileURLToPath(import.meta.url)), "../../../.env");
const current = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";

if (/^VAPID_PUBLIC_KEY=/m.test(current)) {
  console.log("VAPID keys already present in .env");
} else {
  const { publicKey, privateKey } = webpush.generateVAPIDKeys();
  appendFileSync(
    envPath,
    `\n# Web push for streak reminders (generated by pnpm vapid)\nVAPID_PUBLIC_KEY="${publicKey}"\nVAPID_PRIVATE_KEY="${privateKey}"\nVAPID_SUBJECT="mailto:reminders@example.com"\n`,
  );
  console.log("Added VAPID keys to .env");
}
